import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import { Grid, Theme } from '@radix-ui/themes';
import { TopBar } from '@/components/navigation/top-bar';
import { Footer } from '@/components/footer/footer';

import '@radix-ui/themes/styles.css';
import "./globals.css";

const inter = Fira_Code({ subsets: ["latin"], variable: '--font-fira-code', });

export const metadata: Metadata = {
    title: "Dustin Prtell | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={ inter.variable }>
                <Theme appearance={ 'dark' } accentColor={ 'indigo' } className={ 'bg-[--sky-2]' }>
                    <TopBar />
                    <Grid rows={ '1fr auto' } className={ 'h-dvh overflow-y-scroll' }>
                        { children }
                        <Footer/>
                    </Grid>
                </Theme>
            </body>
        </html>
    );
}
