import type { Metadata } from "next";
import { Fira_Code } from "next/font/google";
import { Grid, Theme } from '@radix-ui/themes';
import { TopBar } from '@/components/navigation/top-bar';
import { Footer } from '@/components/footer/footer';

import Image from 'next/image';

import '@radix-ui/themes/styles.css';
import "./globals.css";

const inter = Fira_Code({ subsets: ["latin"], variable: '--font-fira-code', });

export const metadata: Metadata = {
    title: "Dustin Prtell | Portfolio",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
    return (
        <html lang="en">
            <body className={ inter.variable }>
                <Theme appearance={ 'dark' } accentColor={ 'indigo' } className={ 'bg-[--sky-2]' }>
                    <TopBar />
                    <Grid rows={ '1fr auto' } className={ 'relative h-dvh overflow-y-scroll' }>
                        { children }
                        <Footer/>
                        <Image src={ '/background-blur.png' } alt={ 'hero' } fill className='object-cover sm:object-contain ml-0 sm:pl-40 md:pl-60 -z-50 animate-pulse'/>
                    </Grid>
                </Theme>
            </body>
        </html>
    );
}
